right_controller:
  type: position_controllers/JointTrajectoryController
  default: true
  joints:
    - right_s0
    - right_s1
    - right_e0
    - right_e1
    - right_w0
    - right_w1
    - right_w2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_s0: {trajectory: 0.1, goal: 0.5}
      right_s1: {trajectory: 0.1, goal: 0.5}
      right_e0: {trajectory: 0.1, goal: 0.5}
      right_e1: {trajectory: 0.1, goal: 0.5}
      right_w0: {trajectory: 0.1, goal: 0.5}
      right_w1: {trajectory: 0.1, goal: 0.5}
      right_w2: {trajectory: 0.1, goal: 0.5}

left_controller:
  type: position_controllers/JointTrajectoryController
  default: true
  joints:
    - left_s0
    - left_s1
    - left_e0
    - left_e1
    - left_w0
    - left_w1
    - left_w2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_s0: {trajectory: 0.1, goal: 0.1}
      left_s1: {trajectory: 0.1, goal: 0.1}
      left_e0: {trajectory: 0.1, goal: 0.1}
      left_e1: {trajectory: 0.1, goal: 0.1}
      left_w0: {trajectory: 0.1, goal: 0.1}
      left_w1: {trajectory: 0.1, goal: 0.1}
      left_w2: {trajectory: 0.1, goal: 0.1}

  
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
right_hand:
  type: "position_controllers/GripperActionController"
  joint: r_gripper_l_finger_joint
   

left_hand:
  type: "position_controllers/GripperActionController"
  joint: l_gripper_l_finger_joint