controller_list:
# -------------for gazebo UR5---------------------------------
  - name: "right_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  
  - name: "left_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2

# -------------for gazebo gripper---------------------------------
  - name: "right_hand"
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - r_gripper_l_finger_joint_1
  
  - name: "left_hand"
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - l_gripper_l_finger_joint_1
